-
  name: Deploy Pre-Requisites
  hosts: all_hosts
  tasks:
    - name: Install FirewallD
      yum:
        name: firewalld
        state: latest
    - name: Start service FirewallD, if not started
      service:
        name: firewalld
        state: started
    - name: Make sure a FirewallD is running
      systemd:
        name: firewalld
        state: started

-
  name: Deploy and Configure Database
  hosts: db_hosts
  tasks:
    - name: Install MariaDB
      yum:
        name: mariadb-server
        state: latest
    - name: Start service MariaDB, if not started
      service:
        name: mariadb
        state: started
    - name: Make sure a MariaDB is running
      systemd:
        name: mariadb
        state: started
    - name: Add port to firewall
      firewalld:
        zone: public
        port: 3306/tcp
        permanent: yes
        state: enabled
    - name: Reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
    - name: Install python mysql bindings
      yum: 
        name: MySQL-python
        state: latest
      become: yes
      become_method: sudo
    - name: Update MariaDB root password for all root accounts
      mysql_user:
        name: 'ecomuser'
        host: '192.168.1.113'
        check_implicit_admin: yes
        password: 'ecompassword'
        state: present
        priv: "*.*:ALL,GRANT"
        login_user: root 
        login_password: '123456'
    - name: Create a new database  
      mysql_db: 
        name: ecomdb 
        state: present
    - name: Add sample data to database  
      copy: 
        src: db-load-script.sql  
        dest: /tmp/db-load-script.sql 
    - name: Insert sample data into database  
      mysql_db: 
        name: ecomdb 
        state: present
        target: /tmp/db-load-script.sql 

-
  name: Deploy and Configure Web
  hosts: web_hosts
  tasks:
    - name: Install httpd php php-mysql git
      yum:
        name:
          - httpd 
          - php 
          - php-mysql
          - git
        state: latest
    - name: Add port to firewall
      firewalld:
        zone: public
        port: 80/tcp
        permanent: yes
        state: enabled
    - name: Reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
    - name: Configure httpd
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'index.html'
        replace: 'index.php'
    - name: Start service httpd, if not started
      service:
        name: httpd
        state: started
    - name: Make sure a httpd is running
      systemd:
        name: httpd
        state: started
    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
    - name: Download code
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/
        version: master
        update: no
    - name: Update index.php
      replace:
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        replace: '192.168.1.110'